package com.lyh.dietary_assistant.mapper;

import com.lyh.dietary_assistant.pojo.BodyCompositionData;
import com.lyh.dietary_assistant.pojo.BodyCompositionDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BodyCompositionDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int countByExample(BodyCompositionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int deleteByExample(BodyCompositionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int insert(BodyCompositionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int insertSelective(BodyCompositionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    List<BodyCompositionData> selectByExample(BodyCompositionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    BodyCompositionData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int updateByExampleSelective(@Param("record") BodyCompositionData record, @Param("example") BodyCompositionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int updateByExample(@Param("record") BodyCompositionData record, @Param("example") BodyCompositionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int updateByPrimaryKeySelective(BodyCompositionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_body_composition_data
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int updateByPrimaryKey(BodyCompositionData record);
}