package com.lyh.dietary_assistant.mapper;

import com.lyh.dietary_assistant.pojo.Food;
import com.lyh.dietary_assistant.pojo.FoodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int countByExample(FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int deleteByExample(FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int insert(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int insertSelective(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    List<Food> selectByExample(FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    Food selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int updateByExampleSelective(@Param("record") Food record, @Param("example") FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int updateByExample(@Param("record") Food record, @Param("example") FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int updateByPrimaryKeySelective(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    int updateByPrimaryKey(Food record);
}