package com.lyh.dietary_assistant.pojo;

import java.util.Date;

public class DietDiary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diet_diary.id
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diet_diary.owner
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diet_diary.date
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diet_diary.food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Integer food;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diet_diary.portionSize
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Short portionsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diet_diary.threeMeals
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private String threemeals;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diet_diary.id
     *
     * @return the value of t_diet_diary.id
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diet_diary.id
     *
     * @param id the value for t_diet_diary.id
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diet_diary.owner
     *
     * @return the value of t_diet_diary.owner
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diet_diary.owner
     *
     * @param owner the value for t_diet_diary.owner
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diet_diary.date
     *
     * @return the value of t_diet_diary.date
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diet_diary.date
     *
     * @param date the value for t_diet_diary.date
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diet_diary.food
     *
     * @return the value of t_diet_diary.food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Integer getFood() {
        return food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diet_diary.food
     *
     * @param food the value for t_diet_diary.food
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setFood(Integer food) {
        this.food = food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diet_diary.portionSize
     *
     * @return the value of t_diet_diary.portionSize
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Short getPortionsize() {
        return portionsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diet_diary.portionSize
     *
     * @param portionsize the value for t_diet_diary.portionSize
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setPortionsize(Short portionsize) {
        this.portionsize = portionsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diet_diary.threeMeals
     *
     * @return the value of t_diet_diary.threeMeals
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public String getThreemeals() {
        return threemeals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diet_diary.threeMeals
     *
     * @param threemeals the value for t_diet_diary.threeMeals
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setThreemeals(String threemeals) {
        this.threemeals = threemeals == null ? null : threemeals.trim();
    }
}