package com.lyh.dietary_assistant.pojo;

public class Food {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.id
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.owner
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.foodName
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private String foodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.calories
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Float calories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.carbohydrate
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Float carbohydrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.fat
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Float fat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.protein
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Float protein;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.portionSize
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    private Short portionsize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.id
     *
     * @return the value of t_food.id
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.id
     *
     * @param id the value for t_food.id
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.owner
     *
     * @return the value of t_food.owner
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.owner
     *
     * @param owner the value for t_food.owner
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.foodName
     *
     * @return the value of t_food.foodName
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.foodName
     *
     * @param foodname the value for t_food.foodName
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.calories
     *
     * @return the value of t_food.calories
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Float getCalories() {
        return calories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.calories
     *
     * @param calories the value for t_food.calories
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setCalories(Float calories) {
        this.calories = calories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.carbohydrate
     *
     * @return the value of t_food.carbohydrate
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Float getCarbohydrate() {
        return carbohydrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.carbohydrate
     *
     * @param carbohydrate the value for t_food.carbohydrate
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setCarbohydrate(Float carbohydrate) {
        this.carbohydrate = carbohydrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.fat
     *
     * @return the value of t_food.fat
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Float getFat() {
        return fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.fat
     *
     * @param fat the value for t_food.fat
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setFat(Float fat) {
        this.fat = fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.protein
     *
     * @return the value of t_food.protein
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Float getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.protein
     *
     * @param protein the value for t_food.protein
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setProtein(Float protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.portionSize
     *
     * @return the value of t_food.portionSize
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public Short getPortionsize() {
        return portionsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.portionSize
     *
     * @param portionsize the value for t_food.portionSize
     *
     * @mbggenerated Tue Jul 30 20:26:00 CST 2024
     */
    public void setPortionsize(Short portionsize) {
        this.portionsize = portionsize;
    }
}